# Utilisez l'image officielle de MongoDB à partir du hub Docker
FROM mongo:latest
# Aucune action supplémentaire nécessaire car l'image mongo:latest contient tout ce dont nous avons besoin pour MongoDB